[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
let g:lsp_signs_enabled = 1         " enable signs
let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode

let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '‼'}

nmap K :<C-u>LspHover<CR>
nmap <Leader>R :<C-u>LspRename<CR>
nmap <Leader>d :<C-u>LspDefinition<CR>
nmap <Leader>n :<C-u>LspReferences<CR>
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = '''
autocmd BufWritePre <buffer> LspDocumentFormatSync
let g:lsp_settings_root_markers = ['pyproject.toml', 'setup.py', '.git', '.git/']
let g:lsp_settings = {
\   'pylsp-all': {
\     'workspace_config': {
\       'pylsp': {
\         'configurationSources': ['flake8'],
\         'plugins': {
\           'flake8': {
\             'enabled': 0
\           },
\           'mccabe': {
\             'enabled': 0
\           },
\           'pycodestyle': {
\             'enabled': 0
\           },
\           'pylsp_mypy': {
\             'enabled': 1
\           },
\           'pylint': {
\             'enabled': 0,
\             'args': ["--rcfile setup.cfg", "--distable=import-error"]
\           },
\           'pyflakes': {
\             'enabled': 0
\           },
\           'ruff': {
\             'enabled': 1
\           },
\         },
\       },
\     },
\   }
\}
'''
hook_post_source = '''
  " Highlight LSP warnings strongly (like errors)
  highlight link LspWarningHighlight Error
'''

[[plugins]]
repo = 'halkn/lightline-lsp'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
\  'colorscheme': 'solarized',
\  'mode_map': {'c': 'NORMAL'},
\  'active': {
\    'left': [
\       ['mode', 'paste', 'lsp_errors', 'lsp_warnings'],
\       ['readonly', 'filename', 'modified', 'method']
\    ],
\    'right': [
\       ['lineinfo'],
\       ['percent'],
\       ['fileformat', 'fileencoding', 'filetype'],
\    ]
\  },
\  'inactive': {
\    'left': [
\       ['mode', 'paste'],
\       ['readonly', 'filename', 'modified']
\    ],
\    'right': [
\       ['lineinfo'],
\       ['percent'],
\       ['fileformat', 'fileencoding', 'filetype'],
\       ['lsp_errors'],
\    ]
\  },
\  'component_expand': {
\    'lsp_warnings': 'lightline_lsp#warnings',
\    'lsp_errors':   'lightline_lsp#errors',
\  },
\  'component_type': {
\    'lsp_warnings': 'warning',
\    'lsp_errors':   'errors',
\  },
\}
'''

# completions
[[plugins]]
repo='Shougo/ddc.vim'
hook_add = '''
call ddc#custom#patch_global('ui', 'pum')

call ddc#custom#patch_global('sources', ['copilot', 'vim-lsp', 'neosnippet'])

call ddc#custom#patch_global('sourceOptions', #{
      \   copilot: #{
      \     mark: '[copilot]',
      \     matchers: [],
      \     minAutoCompleteLength: 0,
      \     isVolatile: v:true,
      \   },
      \   vim-lsp: #{
      \     mark: '[lsp]',
      \     matchers: [],
      \   },
      \   neosnippet: #{
      \     mark: '[snip]'
      \   },
      \   _: #{
      \     matchers: ['matcher_head'],
      \   },
      \ })

call ddc#custom#patch_global('sourceParams', #{
      \   vim-lsp: #{
      \     ignoreCompleteProvider: v:true,
      \   },
      \ })

call ddc#enable()

'''

## completion ui
[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = '''
inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
inoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
inoremap <silent><expr> <PageUp>
      \ pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' :
      \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
      \ '<PageUp>' : ddc#map#manual_complete()
inoremap <silent><expr> <PageDown>
      \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
      \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
      \ '<PageDown>' : ddc#map#manual_complete()

inoremap <silent><expr> <TAB>
      \ pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' :
      \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
      \ '<TAB>' : ddc#map#manual_complete()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

## copilot
[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
let g:copilot_no_maps = v:true
'''

[[plugins]]
repo = 'Shougo/ddc-source-copilot'

## lsp
[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

let g:neosnippet#snippets_directory='~/snippets/neosnippet'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
nnoremap \e :Fern . -reveal=% -drawer -toggle<CR>
'''

[[plugins]]  # fern 用
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'Shougo/ddu.vim'
# hook_add = '''
# call ddu#custom#patch_global({
#     \   'ui': 'ff',
#     \   'sources': [{'name':'file','params':{}},{'name':'mr'},{'name':'register'},{'name':'buffer'}],
#     \   'sourceOptions': {
#     \     '_': {
#     \       'matchers': ['matcher_substring'],
#     \     },
#     \   },
#     \   'kindOptions': {
#     \     'file': {
#     \       'defaultAction': 'open',
#     \     },
#     \   },
#     \ })
# '''

# [[plugins]]
# repo = 'Shougo/ddu-ui-ff'
# hook_add = '''
# call ddu#custom#patch_global(#{
#     \   ui: 'ff',
#     \ })
# '''
#
# [[plugins]]
# repo = 'Shougo/ddu-source-file_rec'
# hook_add = '''
# call ddu#start(#{ sources: [#{ name: 'file_rec' }] })
# call ddu#custom#patch_global('sourceOptions', #{
#       \   file_rec: #{ path: expand("~") },
#       \ })
# '''
#
# [[plugins]]
# repo = 'Shougo/ddu-kind-file'
#
# [[plugins]]
# repo = 'Shougo/ddu-ui-filer'
# hook_add = '''
# call ddu#custom#patch_global(#{
#     \   ui: 'filer',
#     \   actionOptions: #{
#     \     narrow: #{
#     \       quit: v:false,
#     \     },
#     \   },
#     \ })
# '''
#
# [[plugins]]
# repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = [
  \ '~/git/template'
  \]
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config={'*': {'split': ''}}
set splitright
let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
nmap <Leader>r :<C-u>QuickRun<CR>

let g:quickrun_config['cuda'] = {
  \'command' : 'nvcc',
  \}

let g:quickrun_config['cpp'] = {
  \'command' : 'g++',
  \'cmdopt' : '-std=c++14',
  \}

if g:is_pipenv_active
  let g:quickrun_config['python'] = {
      \'command' : 'pipenv',
      \'exec': ['%c run python %s']
      \}
  let g:quickrun_config['yaml'] = {
      \'command' : 'pipenv',
      \'exec': ['%c run yq . %s']
      \}
elseif g:is_poetry_active
  let g:quickrun_config['python'] = {
      \'command' : 'poetry',
      \'exec': ['%c run python %s']
      \}
  let g:quickrun_config['yaml'] = {
      \'command' : 'poetry',
      \'exec': ['%c run yq . %s']
      \}
elseif g:is_pyenv_system
  let g:quickrun_config['python'] = {
      \'command' : 'python3'
      \}
  let g:quickrun_config['yaml'] = {
      \'command' : 'yq',
      \'exec': ['$c . %s']
      \}
else
  let g:quickrun_config['python'] = {
      \'command' : 'python'
      \}
  let g:quickrun_config['yaml'] = {
      \'command' : 'yq',
      \'exec': ['%c . %s']
      \}
endif
'''

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_fileTypeExclude = ['help']
set list lcs=tab:\|\ ""
let g:indentLine_color_term = 239

'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
nnoremap <leader>t :TagbarToggle<CR>
'''

# [[plugins]]
# repo = 'editorconfig/editorconfig-vim'
# hook_add = '''
#   let g:EditorConfig_core_mode = 'external_command'
# '''

# html
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

# tex
[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'


[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

# javascript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = 'typescript'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'jsx'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# [[plugins]]
# repo = 'claco/jasmine/vim'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'mtscout6/vim-cjsx'
on_ft = 'cjsx'

[[plugins]]
repo = 'ryym/vim-riot'
on_ft = 'tag'

# scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_gocode_unimported_packages = 1
" function! OnGo() abort
"   autocmd InsertLeave <buffer> GoImports
" endfunction
" autocmd FileType go call OnGo()
'''

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
  let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'
hook_source = '''
    " rustドキュメントのパス指定
    let g:rust_doc#downloaded_rust_doc_dir = '{rustドキュメントのフルパス}'
'''

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# vim
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'

[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
on_ft = 'help'

# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
  let g:tex_conceal = ""
  let g:vim_markdown_math = 1
'''
# coq
# [[plugins]]
# repo = 'jvoorhis/coq.vim'
# on_ft = 'coq'
# [[plugins]]
# repo = 'vim-scripts/CoqIDE'
# on_ft = 'coq'

[[plugins]]
repo = 'madox2/vim-ai'
hook_add = '''
  let g:vim_ai_token_file_path = '~/.config/openai.token'
'''

# [[plugins]]
# repo = 'Robitx/gp.nvim'
# hook_add = '''
# lua require('gp').setup()
# '''
